### ISSUE TITLE
More accurate results

### ISSUE THREAD

**Issue by k4k4r07** [ahmedcj/bufferover#1]
Hello @ahmedcj 
I think ```curl -s https://tls.bufferover.run/dns?q=${1}``` instead of this the request should be ```curl -s https://tls.bufferover.run/dns?q=.${1}``` . This will give more accurate results.

Thanks

**Comment by ahmedcj** [comment]
Hi @k4k4r07 - Thank you for your intention to help.
Yes, You're totally right, But I made the script more flexible, You can extract subdomains by just using the [-s] option.
Thank you.

**Comment by k4k4r07** [comment]
Thanks for the response.
